name: Auto Format

on:
  schedule:
    - cron: "0 7 * * 1,4"  # Mon/Thu 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install black ruff

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install --global prettier

      - run: black . --exclude '\.github/workflows/'

      - run: |
          ruff format . --exclude .github/workflows/
          ruff check . --fix --exclude .github/workflows/

      - run: prettier --write "**/*.{js,jsx,ts,tsx,css,scss,md,json,yml,yaml,html,mdx}" || true

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: auto-format via Black/Ruff/Prettier" || echo "No changes"
          git push



