name: Cleanup Unused Imports/Vars

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 2"

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ruff autoflake

      - run: |
          ruff check . --fix --select F401,F841 --exclude .github/workflows/

      - run: |
          autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --remove-duplicate-keys --expand-star-imports $(git ls-files "*.py")

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: remove unused imports/variables"
          branch: cleanup-unused/update
          title: "Cleanup unused imports/variables"
          body: |
            This PR removes unused imports and variables using Ruff and Autoflake.
