name: Cleanup Unused Imports/Vars

on:
  schedule:
    - cron: "0 6 * * 2"  # Tuesdays
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ruff autoflake

      - run: |
          ruff check . --fix --select F401,F841 --exclude .github/workflows/
          autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --remove-duplicate-keys --expand-star-imports $(git ls-files "*.py")

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: remove unused imports/variables" || echo "No changes"
          git push

