name: Code Graph Visualization

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3"

permissions:
  contents: write

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install graphviz

      - run: python scripts/code_graph.py

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add diagrams/
          git commit -m "chore(diagrams): update code graphs" || echo "No changes"
          git push
