name: License Header Injection

on:
  schedule:
    - cron: "0 5 * * 3"  # Wednesdays
  workflow_dispatch:

permissions:
  contents: write

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install regex

      - run: python scripts/add_license_headers.py

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: add missing license headers" || echo "No changes"
          git push
